
TOP=../..
.include "$(TOP)/mk/os161.config.mk"

# Just add new directories at the end of the line below.
SUBDIRS= example 
SUBDIRS= writeConsole
SUBDIRS= timeOfDay
SUBDIRS= getpid
SUBDIRS= stubtest
SUBDIRS= onefork
SUBDIRS= fork
SUBDIRS= forkchain
SUBDIRS= forkfan

.include "$(TOP)/mk/os161.subdir.mk"
